package proyecto.hibernate.beans;

// Generated 21-may-2013 17:32:08 by Hibernate Tools 3.4.0.CR1

/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private AuthoritiesId id;
	private Users users;

	public Authorities() {
	}

	public Authorities(AuthoritiesId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public AuthoritiesId getId() {
		return this.id;
	}

	public void setId(AuthoritiesId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
