package proyecto.hibernate.beans;

// Generated 21-may-2013 17:32:08 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Contacts generated by hbm2java
 */
public class Contacts implements java.io.Serializable {

	private String contactUsername;
	private Users users;
	private String companyName;
	private String professionalRole;
	private String name;
	private String surname;
	private String address;
	private String city;
	private String country;
	private String email;
	private String mobile;
	private String phone;
	private String note;
	private Set<ContactsList> contactsListsForContactListed = new HashSet<ContactsList>(0);
	private Set<ContactsList> contactsListsForContactMain = new HashSet<ContactsList>(0);

	public Contacts() {
	}

	public Contacts(Users users, String companyName, String professionalRole,
			String name, String surname, String address, String city,
			String country, String email, String mobile, String phone,
			String note) {
		this.users = users;
		this.companyName = companyName;
		this.professionalRole = professionalRole;
		this.name = name;
		this.surname = surname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.note = note;
	}

	public Contacts(Users users, String companyName, String professionalRole,
			String name, String surname, String address, String city,
			String country, String email, String mobile, String phone,
			String note, Set<ContactsList> contactsListsForContactListed,
			Set<ContactsList> contactsListsForContactMain) {
		this.users = users;
		this.companyName = companyName;
		this.professionalRole = professionalRole;
		this.name = name;
		this.surname = surname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.note = note;
		this.contactsListsForContactListed = contactsListsForContactListed;
		this.contactsListsForContactMain = contactsListsForContactMain;
	}

	public String getContactUsername() {
		return this.contactUsername;
	}

	public void setContactUsername(String contactUsername) {
		this.contactUsername = contactUsername;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getProfessionalRole() {
		return this.professionalRole;
	}

	public void setProfessionalRole(String professionalRole) {
		this.professionalRole = professionalRole;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<ContactsList> getContactsListsForContactListed() {
		return this.contactsListsForContactListed;
	}

	public void setContactsListsForContactListed(
			Set<ContactsList> contactsListsForContactListed) {
		this.contactsListsForContactListed = contactsListsForContactListed;
	}

	public Set<ContactsList> getContactsListsForContactMain() {
		return this.contactsListsForContactMain;
	}

	public void setContactsListsForContactMain(
			Set<ContactsList> contactsListsForContactMain) {
		this.contactsListsForContactMain = contactsListsForContactMain;
	}

}
